### PR TITLE
build + push multiple tags

### PR DESCRIPTION
**Pull request by DrPsychick**
Reason:
* `xenial` is outdated
* add `.circleci` because my travis-ci account is out of credits -> I needed to build with something else
* Images are pushed to docker, if you wanna test: https://hub.docker.com/r/drpsychick/steamcmd/tags?page=1&ordering=last_updated

### CODE REVIEW

**Comment by DrPsychick** [comment]
Hi @thmhoag any chance you could check if this PR is acceptable?

**Comment by DrPsychick** [comment]
@thmhoag I'd love to switch to using your image, if you accept the PR. If not I'll be force to publish my own image - but I'd like to avoid that.

**Comment by thmhoag** [comment]
Hey @DrPsychick, sorry for the delay here. This looks solid and I'd like to add it in. Building for `xenial` on up makes sense, they can simply be tagged accordingly. 

The only thing I might change about this PR is that I'd like to continue to just use the Dockerhub builds that I currently have setup. This is mostly just to stay consistent with my other Docker image repos but also so I don't have to maintain a CircleCI build with secrets to push to my Dockerhub repo. Of course, I'll need to modify my existing builds to do one of each tag with the separate build args.

**Comment by DrPsychick** [comment]
> The only thing I might change about this PR is that I'd like to continue to just use the Dockerhub builds that I currently have setup. This is mostly just to stay consistent with my other Docker image repos but also so I don't have to maintain a CircleCI build with secrets to push to my Dockerhub repo. Of course, I'll need to modify my existing builds to do one of each tag with the separate build args.

Sure, I'll remove .circleci then.

Just on note: my experience docker builds are very slow, that's why I moved away from them. Besides, maintaining tags in Github to push to DockerHub accordingly was too much overhead for me.

In case you're interested, this is what I used with travis to build multiple tags: https://github.com/DrPsychick/docker-linuxgsm-ark/blob/master/deploy.sh

**Comment by DrPsychick** [comment]
Hey @thmhoag , what about merging this?

**Comment by DrPsychick** [comment]
closing this, I setup a new repo that builds multiple tags regularly: https://github.com/SickHub/steamcmd

**Pull request closed without merging**
